source 'https://cpdc-eap.googlesource.com/ridesharing-consumer-sdk'
source 'https://github.com/CocoaPods/Specs.git'

target 'ConsumerSampleApp' do
  project 'ConsumerSampleApp'
  platform :ios, '15.0'
  pod 'GoogleRidesharingConsumer'
  target 'UnitTests' do
    inherit! :search_paths
    pod 'GoogleRidesharingConsumer'
  end
end
